SELECT * FROM Gyms
SELECT * FROM Clients
SELECT * FROM Lockers
SELECT * FROM ItemTypes
SELECT * FROM Inventory
SELECT * FROM Employees
SELECT * FROM Tariffs
SELECT * FROM Groups
SELECT * FROM Clients_Groups
SELECT * FROM Subscriptions
SELECT * FROM Activities
SELECT * FROM Coaches
SELECT * FROM CoachActivities
SELECT * FROM GymActivities
SELECT * FROM Schedule